language: c
os: linux
dist: bionic
addons:
  apt:
    packages:
      - gcc-mips64-linux-gnuabi64
      - libc-dev-mips64-cross
      - libc6-mips64-cross
      - qemu-user-static
      - binfmt-support
before_script:
  - update-binfmts --display
  - sudo mkdir "/usr/mips64-linux-gnuabi64/etc"
  - sudo touch "/usr/mips64-linux-gnuabi64/etc/ld.so.cache"
  - sudo mkdir "/etc/qemu-binfmt"
  - sudo ln -sf "/usr/mips64-linux-gnuabi64" "/etc/qemu-binfmt/mips64"
script:
  - mips64-linux-gnuabi64-gcc -ohello hello.c
  - file hello
  - ./hello
