language: c
os: linux
dist: bionic
addons:
  apt:
    packages:
      - gcc-mips64-linux-gnuabi64
      - libc-dev-mips64-cross
      - libc6-mips64-cross
      - qemu-user-static
      - binfmt-support
before_script:
  - update-binfmts --display
script:
  - mips64-linux-gnuabi64-gcc -ohello hello.c
  - file hello
  - ./hello
