language: c
os: linux
dist: bionic
addons:
  apt:
    packages:
      - gcc-mips64-linux-gnuabi64
      - libc-dev-mips64-cross
      - qemu-user-static
script:
  - mips64-linux-gnuabi64-gcc -static  -ohello hello.c
  - file hello
  - ./hello
