language: c
os: linux
dist: bionic
addons:
  apt:
    packages:
      - gcc-mips64-linux-gnuabi64
      - libc-dev-mips64-cross
      - libc6-mips64-cross
      - libc6-mips-cross
      - qemu-user-static
      - binfmt-support
      - dpkg-cross
      - debconf
before_script:
  - update-binfmts --display
  - cat /etc/qemu-binfmt.conf
#  - wget http://ftp.us.debian.org/debian/pool/main/g/glibc/libc6-mips64_2.28-10_mips.deb
#  - sudo dpkg-cross -i -a mips libc6-mips64_2.28-10_mips.deb
#  - sudo dpkg -i libc6-mips64_2.28-10_mips.deb
script:
  - mips64-linux-gnuabi64-gcc -ohello hello.c
  - file hello
  - ./hello
